# Generated by Django 3.1.5 on 2021-01-31 17:00

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Доска')),
                ('board_link', models.URLField(verbose_name='Ссылка на доску')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Курс')),
                ('course_length', models.CharField(choices=[('1', '1 день'), ('4', '4 дня'), ('7', '7 дней'), ('14', '14 дней'), ('30', '30 дней'), ('60', '60 дней')], max_length=50, verbose_name='Длительность курса')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Логин')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, null=True, verbose_name='Фамилия')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=20, region='RU', verbose_name='Телефон')),
                ('email', models.EmailField(max_length=255, verbose_name='Адрес электронной почты')),
                ('middle_name', models.CharField(max_length=150, null=True, verbose_name='Отчество')),
                ('picture', models.ImageField(upload_to='', verbose_name='Фото')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Логин')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, null=True, verbose_name='Фамилия')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=20, region='RU', verbose_name='Телефон')),
                ('email', models.EmailField(max_length=255, verbose_name='Адрес электронной почты')),
                ('year', models.CharField(choices=[('1', '1 класс'), ('2', '2 класс'), ('3', '3 класс'), ('4', '4 класс'), ('5', '5 класс'), ('6', '6 класс'), ('7', '7 класс'), ('8', '8 класс'), ('9', '9 класс'), ('10', '10 класс'), ('11', '11 класс')], max_length=50, verbose_name='Класс')),
                ('parent_name', models.CharField(max_length=150, null=True, verbose_name='Имя родителя')),
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.course', verbose_name='Курс')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Урок')),
                ('lesson_subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('duration', models.CharField(choices=[('45', '45 минут'), ('60', '60 минут')], max_length=50, verbose_name='Длительность занятия')),
                ('board_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.board', verbose_name='Доска')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.student', verbose_name='Ученик')),
                ('teacher_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.teacher', verbose_name='Преподаватель')),
            ],
        ),
    ]
