# Generated by Django 3.1.6 on 2021-02-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото'),
        ),
    ]
