# Generated by Django 3.1.7 on 2021-03-03 17:32

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
            ],
            options={
                'verbose_name': 'новый ученик',
                'verbose_name_plural': 'новые ученики',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=20, region='RU', verbose_name='Телефон')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('picture', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'учитель',
                'verbose_name_plural': 'учителя',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=20, region='RU', verbose_name='Телефон')),
                ('grade', models.CharField(choices=[('1', '1 класс'), ('2', '2 класс'), ('3', '3 класс'), ('4', '4 класс'), ('5', '5 класс'), ('6', '6 класс'), ('7', '7 класс'), ('8', '8 класс'), ('9', '9 класс'), ('10', '10 класс'), ('11', '11 класс')], max_length=50, verbose_name='Класс')),
                ('parent_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя родителя')),
                ('prestudent_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainapp.prestudent', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'ученик',
                'verbose_name_plural': 'ученики',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(default='', max_length=255, verbose_name='Идентификатор доски')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 3, 3, 17, 32, 28, 411366, tzinfo=utc), verbose_name='Время')),
                ('duration', models.CharField(choices=[('45', '45 минут'), ('60', '60 минут')], max_length=50, verbose_name='Длительность занятия')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.student', verbose_name='Ученик')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_length', models.CharField(choices=[('1', '1 занятие'), ('4', '4 занятия'), ('7', '7 занятий'), ('14', '14 занятий'), ('30', '30 занятий'), ('60', '60 занятий')], max_length=50, verbose_name='Длительность курса')),
                ('student_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainapp.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
    ]
