# Generated by Django 3.1.7 on 2021-03-03 18:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210303_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher_id',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 18, 10, 20, 812141, tzinfo=utc), verbose_name='Время'),
        ),
    ]
