# Generated by Django 3.1.7 on 2021-03-22 16:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210322_1739'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 22, 17, 0, tzinfo=utc), verbose_name='Время'),
        ),
    ]
