# Generated by Django 3.1.7 on 2021-03-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210303_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.DateTimeField(verbose_name='Время'),
        ),
    ]
