# Generated by Django 3.1.7 on 2021-03-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210307_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.TimeField(verbose_name='Время'),
        ),
    ]
