# Generated by Django 3.1.7 on 2021-03-22 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210322_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.book', verbose_name='Учебник'),
        ),
    ]
