# Generated by Django 3.1.7 on 2021-03-07 05:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210307_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 5, 35, 46, 726740, tzinfo=utc), verbose_name='Время'),
        ),
    ]
