# Generated by Django 3.1.7 on 2021-03-08 00:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210308_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 0, 24, 14, 88729, tzinfo=utc), verbose_name='Время'),
        ),
    ]
