# Generated by Django 3.1.7 on 2021-03-08 00:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210308_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.DurationField(choices=[(2700, 2700), (3600, '60 минут')], verbose_name='Длительность занятия'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 0, 37, 58, 32278, tzinfo=utc), verbose_name='Время'),
        ),
    ]
