# Generated by Django 3.1.7 on 2021-03-08 00:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20210308_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.TimeField(choices=[('00:45:00', '45 минут'), ('01:00:00', '60 минут')], default='01:00:00', verbose_name='Длительность занятия'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 0, 41, 16, 702113, tzinfo=utc), verbose_name='Время'),
        ),
    ]
