# Generated by Django 3.1.7 on 2021-03-08 00:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20210308_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='time',
        ),
        migrations.AddField(
            model_name='lesson',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 0, 52, 38, 421279, tzinfo=utc), verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.CharField(choices=[(2700, '45 минут'), (3600, '60 минут')], default=3600, max_length=50, verbose_name='Длительность занятия'),
        ),
    ]
